import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
      },
      modalOverlayTouch: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
      },
      modalContainer: {
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        height: '80%',
        width: '100%',
      },
      modalHandleContainer: {
        alignItems: 'center',
        paddingTop: 12,
        paddingBottom: 8,
      },
      modalHandle: {
        width: 36,
        height: 4,
        backgroundColor: '#E0E0E0',
        borderRadius: 2,
      },
      tabContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        marginBottom: 16,
      },
      tabButton: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        position: 'relative',
      },
      activeTabButton: {
        borderBottomWidth: 0,
      },
      tabText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#888',
      },
      activeTabText: {
        color: '#333',
        fontWeight: '600',
      },
      activeTabIndicator: {
        position: 'absolute',
        bottom: 0,
        left: 30,
        right: 30,
        height: 3,
        backgroundColor: '#333',
        borderRadius: 1.5,
      },
      scrollContentContainer: {
        paddingHorizontal: 20,
        paddingBottom: 30,
      },
      
      // Type Selection Styles
      typeSelectionContainer: {
        paddingBottom: 40,
      },
      welcomeContainer: {
        alignItems: 'center',
        marginBottom: 24,
      },
      bottleImageContainer: {
        width: 120,
        height: 120,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
      },
      welcomeTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
        marginBottom: 8,
      },
      welcomeSubtitle: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        paddingHorizontal: 20,
        lineHeight: 22,
      },
      securityContainer: {
        flexDirection: 'row',
        backgroundColor: '#f0fff4',
        borderRadius: 12,
        padding: 12,
        marginHorizontal: 10,
        marginVertical: 20,
        borderWidth: 1,
        borderColor: '#d4f5e2',
        alignItems: 'center',
      },
      securityIcon: {
        marginRight: 10,
      },
      securityText: {
        flex: 1,
        fontSize: 14,
        color: '#2f4f4f',
        lineHeight: 20,
      },
      examplesTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 12,
        marginHorizontal: 15,
      },
      examplesContainer: {
        backgroundColor: '#f8f9fa',
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        marginHorizontal: 10,
        borderWidth: 1,
        borderColor: '#f0f0f0',
      },
      exampleItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
      },
      exampleIcon: {
        width: 34,
        height: 34,
        borderRadius: 17,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
      },
      exampleTextContainer: {
        flex: 1,
      },
      exampleTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#444',
        marginBottom: 2,
      },
      exampleText: {
        fontSize: 12,
        color: '#666',
      },
      capsuleTypeTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 12,
        marginHorizontal: 15,
      },
      capsuleTypeCards: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 10,
      },
      capsuleTypeCard: {
        width: (width - 80) / 2,
        backgroundColor: '#f9f9f9',
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      capsuleTypeIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
      },
      capsuleTypeDescription: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
      },
      capsuleTypeCardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
        textAlign: 'center',
      },
      // Form Styles
      capsuleFormContainer: {
        position: 'relative',
        paddingTop: 10,
        paddingBottom: 40,
      },
      formHeaderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
        paddingHorizontal: 4,
      },
      backButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
      },
      formTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
        flex: 1,
      },
      placeholderView: {
        width: 32,
        height: 32,
      },
      formSection: {
        marginBottom: 24,
      },
      sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
      },
      sectionSubtitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: 15,
      },
      inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
      },
      inputIcon: {
        marginRight: 10,
      },
      textInput: {
        flex: 1,
        fontSize: 16,
        color: '#333',
      },
      contentTypeScroll: {
        marginBottom: 5,
      },
      contentTypeCard: {
        width: 150,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginRight: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        position: 'relative',
      },
      contentTypeIcon: {
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
      },
      contentTypeTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
      },
      contentTypeSubtitle: {
        fontSize: 12,
        color: '#888',
        marginBottom: 10,
      },
      addButtonContainer: {
        alignItems: 'flex-end',
      },
      emptyContentPreview: {
        backgroundColor: '#f9f9f9',
        borderRadius: 12,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#ddd',
        padding: 30,
        alignItems: 'center',
        justifyContent: 'center',
      },
      emptyContentText: {
        fontSize: 14,
        color: '#999',
        marginTop: 10,
      },
      timeSelectionContainer: {
        marginTop: 10,
        marginBottom: 20,
      },
      timeOptionsLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 10,
      },
      quickTimeOptions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
      },
      quickTimeButton: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: '#f5f5f5',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
        marginRight: 5,
      },
      quickTimeButtonActive: {
        backgroundColor: '#333',
        borderColor: '#222',
      },
      quickTimeText: {
        fontSize: 13,
        color: '#666',
        fontWeight: '500',
      },
      quickTimeTextActive: {
        fontSize: 13,
        color: '#fff',
        fontWeight: '600',
      },
      dateDisplayContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f9f9f9',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e8e8e8',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
      },
      dateIconWrapper: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
      },
      dateDisplayText: {
        flex: 1,
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
      },
      datePickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f7fd',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
      },
      datePickerButtonText: {
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
        marginRight: 4,
      },
      locationSelectionContainer: {
        marginTop: 10,
        marginBottom: 20,
      },
      mapPreviewPlaceholder: {
        backgroundColor: '#eef2f5',
        borderRadius: 16,
        height: 160,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#e0e7ee',
        overflow: 'hidden',
      },
      mapIconWrapper: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#3498db',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      mapPreviewText: {
        fontSize: 15,
        color: '#666',
        marginTop: 8,
      },
      radiusLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 10,
      },
      radiusOptions: {
        flexDirection: 'row',
        marginBottom: 20,
      },
      radiusOption: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        marginHorizontal: 3,
        borderRadius: 8,
      },
      radiusOptionActive: {
        backgroundColor: '#3498db',
        borderColor: '#2980b9',
      },
      radiusText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#666',
      },
      radiusTextActive: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
      },
      addTimeToLocationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f7fd',
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 10,
        alignSelf: 'flex-start',
        borderWidth: 1,
        borderColor: '#d5e8f9',
      },
      addTimeIconWrapper: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#3498db',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
      },
      addTimeToLocationText: {
        fontSize: 14,
        color: '#3498db',
        fontWeight: '500',
      },
      recipientOptionsContainer: {
        flexDirection: 'row',
        marginTop: 16,
      },
      recipientOption: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 12,
        marginHorizontal: 5,
        backgroundColor: '#f9f9f9',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#eee',
      },
      recipientOptionActive: {
        backgroundColor: '#f0f7fd',
        borderColor: '#3498db',
      },
      recipientIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#f5f5f5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#e0e0e0',
      },
      recipientIconWrapperActive: {
        backgroundColor: '#333',
        borderColor: '#222',
      },
      recipientText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
      },
      recipientTextActive: {
        color: '#333',
        fontWeight: '600',
      },
      formActions: {
        flexDirection: 'row',
        marginTop: 30,
        marginBottom: 10,
      },
      cancelButton: {
        flex: 1,
        backgroundColor: '#f0f0f0',
        paddingVertical: 14,
        borderRadius: 12,
        marginRight: 8,
        alignItems: 'center',
      },
      cancelButtonText: {
        fontSize: 16,
        color: '#666',
        fontWeight: '500',
      },
      createButton: {
        flex: 2,
        backgroundColor: '#333',
        paddingVertical: 14,
        borderRadius: 12,
        marginLeft: 8,
        alignItems: 'center',
      },
      createButtonDisabled: {
        backgroundColor: '#ccc',
      },
      createButtonText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '600',
      },
      // My Capsules Styles
      myCapsuleContainer: {
        paddingBottom: 40,
      },
      myCapsuleTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 20,
        textAlign: 'center',
      },
      filterContainer: {
        flexDirection: 'row',
        marginBottom: 20,
        paddingHorizontal: 10,
      },
      filterButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 10,
        marginHorizontal: 4,
        borderRadius: 20,
        alignItems: 'center',
      },
      activeFilterButton: {
        backgroundColor: '#3498db',
      },
      filterText: {
        fontSize: 14,
        color: '#666',
      },
      activeFilterText: {
        fontSize: 14,
        color: '#fff',
        fontWeight: '500',
      },
      emptyCapsuleContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 30,
        paddingBottom: 30,
      },
      emptyTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#666',
        marginTop: 16,
        marginBottom: 8,
      },
      emptySubtitle: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
        paddingHorizontal: 30,
      },
      addedContentsContainer: {
        padding: 10,
      },
      contentPreviewItem: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        marginBottom: 10,
      },
      contentPreviewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
      },
      contentTypeIndicator: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#3498db',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
      },
      contentPreviewTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
      },
      contentRemoveButton: {
        marginLeft: 'auto',
      },
      contentPreviewBody: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      textPreview: {
        flex: 1,
        fontSize: 14,
        color: '#666',
      },
      imagePreview: {
        width: 100,
        height: 100,
        borderRadius: 8,
      },
      videoPreviewContainer: {
        position: 'relative',
        width: 100,
        height: 100,
        borderRadius: 8,
        overflow: 'hidden',
      },
      videoPreview: {
        width: '100%',
        height: '100%',
      },
      videoPreviewOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      audioPreviewContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#f9f9f9',
        borderRadius: 8,
      },
      audioPreviewText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 10,
      },
      timeConstraintContainer: {
        marginTop: 10,
        marginBottom: 20,
      },
      timeConstraintLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 10,
      },
      miniMapPreview: {
        width: '100%',
        height: '100%',
        borderRadius: 8,
      },
      loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      loadingText: {
        fontSize: 16,
        color: '#666',
        marginTop: 10,
      },
      capsulesList: {
        padding: 10,
      },
      capsuleCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#f0f0f0',
      },
      capsuleCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
      },
      capsuleTypeIndicator: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#3498db',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
      },
      locationIndicator: {
        backgroundColor: '#e74c3c',
      },
      timeIndicator: {
        backgroundColor: '#2ecc71',
      },
      capsuleCardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        flex: 1,
      },
      capsuleStatusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 16,
        marginLeft: 'auto',
      },
      openedBadge: {
        backgroundColor: '#e1f5fe',
      },
      pendingBadge: {
        backgroundColor: '#fff8e1',
      },
      capsuleStatusText: {
        fontSize: 14,
        fontWeight: '600',
      },
      openedStatusText: {
        color: '#0288d1',
      },
      pendingStatusText: {
        color: '#ffa000',
      },
      capsuleCardBody: {
        paddingVertical: 10,
      },
      contentPreviewRow: {
        marginBottom: 14,
      },
      contentTypeIcons: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
      },
      miniContentTypeIndicator: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        marginBottom: 6,
      },
      extraContentIndicator: {
        backgroundColor: '#f0f7fd',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 14,
        marginLeft: 6,
      },
      extraContentText: {
        fontSize: 12,
        color: '#3498db',
        fontWeight: '600',
      },
      noContentText: {
        fontSize: 14,
        color: '#999',
        fontStyle: 'italic',
      },
      capsuleInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        paddingVertical: 6,
      },
      capsuleInfoText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
      },
      capsuleDetailsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 6,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        marginTop: 6,
      },
      capsuleDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 16,
      },
      capsuleDetailText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
      },
      capsuleActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 14,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
      },
      capsuleActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 8,
      },
      capsuleActionText: {
        fontSize: 14,
        fontWeight: '500',
        marginLeft: 6,
      },
      timeRemainingBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e1f5fe',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 16,
      },
      timeRemainingText: {
        fontSize: 14,
        color: '#0288d1',
        fontWeight: '500',
        marginLeft: 6,
      },
    
      // Metin Girişi Modal Stilleri
      textInputModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
      },
      textInputModalContainer: {
        backgroundColor: 'white',
        width: '100%',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
      },
      textInputModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
      },
      textInputModalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
      },
      textInputModalCloseButton: {
        padding: 5,
      },
      textInputModalInput: {
        backgroundColor: '#f9f9f9',
        borderWidth: 1,
        borderColor: '#eee',
        borderRadius: 12,
        padding: 15,
        minHeight: 120,
        fontSize: 16,
        color: '#333',
        textAlignVertical: 'top',
        marginBottom: 20,
      },
      textInputModalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
      },
      textInputModalCancelButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        marginRight: 10,
      },
      textInputModalCancelText: {
        fontSize: 16,
        color: '#666',
      },
      textInputModalConfirmButton: {
        backgroundColor: '#333',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
      },
      textInputModalConfirmText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '500',
      },
    
      // Konum Seçici Modal Stilleri
      locationPickerContainer: {
        flex: 1,
        backgroundColor: '#fff',
      },
      locationPickerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
      },
      locationPickerBackButton: {
        padding: 5,
      },
      locationPickerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
      },
      locationPickerConfirmButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
      },
      locationPickerConfirmText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
      },
      mapContainer: {
        flex: 1,
        position: 'relative',
      },
      mapView: {
        ...StyleSheet.absoluteFillObject, // Haritanın tam kapsayıcısını doldurmasını sağlar
      },
      locationPermissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
      },
      locationPermissionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginTop: 20,
        marginBottom: 10,
      },
      locationPermissionText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 20,
        lineHeight: 24,
      },
      locationPermissionButton: {
        backgroundColor: '#333',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
      },
      locationPermissionButtonText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '500',
      },
      locationPickerControls: {
        backgroundColor: '#fff',
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#eee',
      },
      locationPickerHelpText: {
        fontSize: 14,
        color: '#666',
        marginBottom: 12,
        textAlign: 'center',
      },
      useCurrentLocationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#333',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
      },
      useCurrentLocationText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '500',
        marginLeft: 8,
      },
    
      // Tarih Seçici Modal Stilleri
      datePickerModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
      },
      datePickerContainer: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        padding: 20,
      },
      datePickerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
      },
      datePickerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
      },
      datePickerCancelText: {
        fontSize: 16,
        color: '#666',
      },
      datePickerConfirmText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
      },
      datePickerPlaceholder: {
        height: 250,
        justifyContent: 'center',
        alignItems: 'center',
      },
      datePickerPlaceholderText: {
        fontSize: 16,
        color: '#666',
      },
      selectedRecipientsContainer: {
        marginTop: 15,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
      },
      selectedRecipientsTitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: 10,
      },
      selectedRecipientsScroll: {
        flexDirection: 'row',
      },
      recipientChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
      },
      recipientAvatar: {
        width: 24,
        height: 24,
        borderRadius: 12,
        marginRight: 8,
      },
      recipientLetterAvatar: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
      },
      recipientLetterText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
      },
      recipientChipName: {
        fontSize: 14,
        color: '#333',
      },
      editRecipientsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#e0e0e0',
      },
      editRecipientsText: {
        fontSize: 14,
        color: '#333',
        marginLeft: 4,
      },
      contentGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginHorizontal: -5, // Negatif margin ile grid dengesi sağlanıyor
      },
      contentGridItem: {
        width: (width - 60) / 2, // 2 kolon grid, her iki taraftan padding hesaplanarak
        marginHorizontal: 5,
        marginBottom: 10,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#f0f0f0',
      },
      filePreviewContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        backgroundColor: '#f9f9f9',
        borderRadius: 8,
      },
      fileInfoContainer: {
        flex: 1,
        marginLeft: 10,
      },
      filePreviewName: {
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
      },
      filePreviewSize: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
      },
      premiumNoteContainer: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: '#f39c12',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 10,
      },
      premiumNoteText: {
        color: '#fff',
        fontSize: 8,
        fontWeight: 'bold',
      },
      recipientsPreviewContainer: {
        marginTop: 10,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
      },
      recipientsPreviewLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
        fontWeight: '500',
      },
      recipientsChipContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
      },
      miniRecipientChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 16,
        marginRight: 6,
        marginBottom: 6,
        borderWidth: 1,
        borderColor: '#e8e8e8',
      },
      miniRecipientAvatar: {
        width: 20,
        height: 20,
        borderRadius: 10,
        marginRight: 4,
      },
      miniRecipientLetterAvatar: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#3498db',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 4,
      },
      miniRecipientLetterText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
      },
      miniRecipientName: {
        fontSize: 12,
        color: '#333',
        maxWidth: 80,
      },
      miniRecipientMore: {
        backgroundColor: '#e1f5fe',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 16,
        marginBottom: 6,
      },
      miniRecipientMoreText: {
        fontSize: 12,
        color: '#0288d1',
        fontWeight: '500',
      },
      resultOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        zIndex: 999,
        padding: 20,
        backdropFilter: 'blur(6px)',
      },
      successOverlay: {
        backgroundColor: 'rgba(46, 204, 113, 0.85)',
      },
      errorOverlay: {
        backgroundColor: 'rgba(231, 76, 60, 0.85)',
      },
      resultIconContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 30,
        borderWidth: 3,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
      },
      resultMessage: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        marginBottom: 12,
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
      },
      resultSubMessage: {
        fontSize: 16,
        color: '#fff',
        textAlign: 'center',
        opacity: 0.9,
        maxWidth: '80%',
        lineHeight: 22,
      },
      resultButton: {
        marginTop: 30,
        paddingVertical: 15,
        paddingHorizontal: 40,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
      },
      resultButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#e74c3c',
        letterSpacing: 0.5,
      },
});
