import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

const { width } = Dimensions.get('window');
const POST_SIZE = width / 3 - 2;
const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 44 : StatusBar.currentHeight || 0;

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#FFF',
        paddingTop: Platform.OS === 'android' ? STATUSBAR_HEIGHT : 0,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#FFF',
    },
    headerSection: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: Platform.OS === 'ios' ? 50 : 10,
        paddingHorizontal: 16,
        paddingBottom: 10,
    },
    backButton: {
        padding: 8,
    },
    headerTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#333',
        marginLeft: 8,
    },
    menuButton: {
        padding: 8,
    },
    scrollContent: {
        paddingBottom: 20,
    },
    profileHeader: {
        padding: 16,
    },
    profileTopSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    profileImageContainer: {
        marginRight: 20,
        shadowColor: '#25D220',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
        borderRadius: 50,
    },
    profileImage: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#25D220',
    },
    statsContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    statCard: {
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    statLabel: {
        fontSize: 12,
        color: '#666',
    },
    profileInfo: {
        marginBottom: 16,
    },
    nameContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    name: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 4,
    },
    username: {
        fontSize: 14,
        color: '#666',
        marginBottom: 4,
    },
    bioText: {
        fontSize: 14,
        color: '#8E8E8E',
        lineHeight: 20,
        marginTop: 4,
    },
    actionButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    followButton: {
        flex: 1,
        backgroundColor: '#25D220',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginRight: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    followButtonText: {
        color: '#FFF',
        fontWeight: '600',
    },
    messageButton: {
        flex: 1,
        backgroundColor: '#F0F0F0',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginLeft: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    messageButtonText: {
        color: '#333',
        fontWeight: '600',
    },
    friendButton: {
        flex: 1,
        backgroundColor: '#4CAF50',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginRight: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    friendButtonText: {
        color: '#FFF',
        fontWeight: '600',
    },
    pendingButton: {
        flex: 1,
        backgroundColor: '#FFA000',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginRight: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    pendingButtonText: {
        color: '#FFF',
        fontWeight: '600',
    },
    acceptButton: {
        flex: 1,
        backgroundColor: '#25D220',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginRight: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    acceptButtonText: {
        color: '#FFF',
        fontWeight: '600',
    },
    postsContainer: {
        marginTop: 16,
    },
    postsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderTopWidth: 0,
        borderBottomWidth: 1,
        borderColor: '#EFEFEF',
        marginLeft: 0,
    },
    postsHeaderText: {
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    postsGrid: {
        paddingTop: 2,
    },
    postItem: {
        width: POST_SIZE,
        height: POST_SIZE,
        margin: 1,
    },
    postImage: {
        width: '100%',
        height: '100%',
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    emptyText: {
        fontSize: 16,
        color: '#666',
        marginTop: 12,
    },
    loadingContainer: {
        padding: 40,
        alignItems: 'center',
    },
    loadingText: {
        fontSize: 16,
        color: '#666',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        backgroundColor: '#fff',
        zIndex: 1,
    },
    modalContent: {
        paddingBottom: 20,
    },
    privateProfileContainer: {
        flex: 1,
        padding: 16,
    },
    privateProfileContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
        marginTop: 40,
    },
    lockIconContainer: {
        marginBottom: 20,
    },
    privateProfileTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 12,
        textAlign: 'center',
    },
    privateProfileText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        lineHeight: 24,
    },
    tabButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    activeTabButton: {
        borderBottomColor: '#25D220',
    },
    actionSheetOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'flex-end',
    },
    actionSheetContainer: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 16,
    },
    actionSheetItem: {
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    actionSheetItemText: {
        fontSize: 16,
        color: '#333',
        textAlign: 'center',
    },
    actionSheetDestructive: {
        backgroundColor: '#FFF0F0',
    },
    actionSheetDestructiveText: {
        color: '#FF3B30',
    },
    actionSheetCancel: {
        marginTop: 8,
    },
    editButton: {
        flex: 1,
        backgroundColor: '#25D220',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginRight: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    editButtonText: {
        color: '#FFF',
        fontWeight: '600',
    },
    shareButton: {
        flex: 1,
        backgroundColor: '#F0F0F0',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginLeft: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    shareButtonText: {
        color: '#333',
        fontWeight: '600',
    },
    profileImageModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1000,
    },
    profileImageModalOverlay: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileImageModalContent: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
    },
    profileImageModalImage: {
        width: Dimensions.get('window').width * 0.9,
        height: Dimensions.get('window').width * 0.9,
        borderRadius: 20,
    },
    profileImageModalCloseButton: {
        position: 'absolute',
        top: 50,
        right: 20,
        padding: 10,
        zIndex: 10,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        borderRadius: 20,
    },
    friendsModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    friendsModalCard: {
        backgroundColor: 'white',
        borderRadius: 16,
        width: '85%',
        maxHeight: '70%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 5,
        overflow: 'hidden',
    },
    friendsModalCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    friendsModalCardHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    friendsModalCardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginLeft: 8,
    },
    friendsModalCardClose: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
    },
    friendsModalDivider: {
        height: 1,
        backgroundColor: '#EFEFEF',
        marginHorizontal: 0,
    },
    friendsModalCardSubtitle: {
        fontSize: 14,
        color: '#666',
        marginTop: 12,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    friendsModalSearchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 10,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    friendsModalSearchInput: {
        flex: 1,
        fontSize: 14,
        color: '#333',
        padding: 0,
        height: 20,
    },
    friendsModalLoadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    friendsModalLoadingText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
        marginTop: 10,
    },
    friendsModalListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        backgroundColor: 'transparent',
    },
    friendsModalListItemAvatarContainer: {
        position: 'relative',
        marginRight: 12,
    },
    friendsModalListItemAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(37, 210, 32, 0.2)',
    },
    friendsModalListItemAvatarPlaceholder: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F0F0F0',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(37, 210, 32, 0.2)',
    },
    friendsModalListItemInitial: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#757575',
    },
    friendsModalListItemInfo: {
        flex: 1,
    },
    friendsModalListItemName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 2,
    },
    friendsModalEmptyContainer: {
        padding: 30,
        alignItems: 'center',
        justifyContent: 'center',
    },
    friendsModalEmptyText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        marginTop: 12,
    },
    verificationBadge: {
        marginLeft: 4,
        alignSelf: 'center',
        transform: [{ translateY: 0 }]
    },
    nameVerificationBadge: {
        marginLeft: 8,
        transform: [{ translateY: -1 }]
    },
    postSkeletonItem: {
        width: POST_SIZE,
        height: POST_SIZE,
        margin: 1,
        borderRadius: 4,
        overflow: 'hidden',
    },
});

export default styles; 